--liquibase formatted sql

--changeset credit-apply:create-table-applications
CREATE TABLE IF NOT EXISTS loan_applications (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    applicant_income INTEGER NOT NULL,
    credit_load INTEGER NOT NULL,
    credit_score INTEGER NOT NULL,
    loan_amount INTEGER NOT NULL,
    loan_term INTEGER NOT NULL,
    status SMALLINT,
    CONSTRAINT loan_applications_pkey PRIMARY KEY (id),
    CONSTRAINT loan_applications_status_check CHECK (status >= 0 AND status <= 2)
);
